language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t artburlaka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true artburlaka/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "ReactApp-stage"
  bucket_name: "elasticbeanstalk-us-east-1-711637092958"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
